### PR TITLE
fix: finding store location on a drive that has no home dir

### PR DESCRIPTION
**Pull request by zkochan**
close pnpm/pnpm#2072

### CODE REVIEW

**Comment by zkochan** [comment]
cc @jeffrson

**Comment by zkochan** [comment]
We'll have to cover these with some tests but we'll have to use some mocked filesystem

**Comment by ExE-Boss** [comment]
We should probably also move this package [to the **pnpm** monorepo](https://github.com/pnpm/pnpm).

**Comment by zkochan** [comment]
I agree, but unfortunately, the tests in the pnpm monorepo sometimes run for more than an hour on AppVeyor. So I'd optimize that before moving more packages

**Pull request merged**
